name: Deploy Rust Web Server to GKE

on:
  push:
    branches:
      - main
      
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_ZONE: ${{ secrets.GKE_CLUSTER_ZONE }}
  GKE_DEPLOYMENT_NAME: my-web-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build Rust application
        run: cargo build --release

      - name: Build Docker image
        run: docker build -t gcr.io/$PROJECT_ID/$GKE_DEPLOYMENT_NAME:latest .

      - name: Configure Docker authentication
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Push Docker image to Google Container Registry
        run: docker push gcr.io/$PROJECT_ID/$GKE_DEPLOYMENT_NAME:latest

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: $PROJECT_ID

      - name: Configure kubectl
        run: gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE

      - name: Deploy to GKE
        run: |
          kubectl set image deployment/$GKE_DEPLOYMENT_NAME \
            $GKE_DEPLOYMENT_NAME=gcr.io/$PROJECT_ID/$GKE_DEPLOYMENT_NAME:latest
